global:
  scrape_interval: 5s  # Scrape every 5 seconds

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'order-service'
    static_configs:
      - targets: ['hosts.docker.internal:50053']

  - job_name: 'user-service'
    static_configs:
      - targets: ['hosts.docker.internal:50052']
