# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api_gateway.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'api_gateway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61pi_gateway.proto\"<\n\x13RouteRequestMessage\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"(\n\x14RouteResponseMessage\x12\x10\n\x08response\x18\x01 \x01(\t2R\n\x11\x41PIGatewayService\x12=\n\x0cRouteRequest\x12\x14.RouteRequestMessage\x1a\x15.RouteResponseMessage\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_gateway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTEREQUESTMESSAGE']._serialized_start=21
  _globals['_ROUTEREQUESTMESSAGE']._serialized_end=81
  _globals['_ROUTERESPONSEMESSAGE']._serialized_start=83
  _globals['_ROUTERESPONSEMESSAGE']._serialized_end=123
  _globals['_APIGATEWAYSERVICE']._serialized_start=125
  _globals['_APIGATEWAYSERVICE']._serialized_end=207
# @@protoc_insertion_point(module_scope)
