# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orders.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'orders.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\x12\x06orders\"k\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x0b\n\x03qty\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x05\x12\x13\n\x0btotal_price\x18\x05 \x01(\x05\x12\x0f\n\x07user_id\x18\x06 \x01(\x05\"\x15\n\x07OrderId\x12\n\n\x02id\x18\x01 \x01(\x05\")\n\tOrderList\x12\x1c\n\x05order\x18\x01 \x03(\x0b\x32\r.orders.Order\"\x07\n\x05\x45mpty2\x9b\x01\n\x0cOrderService\x12)\n\tadd_order\x12\r.orders.Order\x1a\r.orders.Order\x12\x30\n\x0c\x64\x65lete_order\x12\x0f.orders.OrderId\x1a\x0f.orders.OrderId\x12.\n\nget_orders\x12\r.orders.Empty\x1a\x11.orders.OrderListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=24
  _globals['_ORDER']._serialized_end=131
  _globals['_ORDERID']._serialized_start=133
  _globals['_ORDERID']._serialized_end=154
  _globals['_ORDERLIST']._serialized_start=156
  _globals['_ORDERLIST']._serialized_end=197
  _globals['_EMPTY']._serialized_start=199
  _globals['_EMPTY']._serialized_end=206
  _globals['_ORDERSERVICE']._serialized_start=209
  _globals['_ORDERSERVICE']._serialized_end=364
# @@protoc_insertion_point(module_scope)
