# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import orders_pb2 as orders__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\x1a\x0corders.proto\"R\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x1d\n\x06orders\x18\x04 \x03(\x0b\x32\r.orders.Order\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x08UserList\x12\x19\n\x04user\x18\x01 \x03(\x0b\x32\x0b.users.User\"\x07\n\x05\x45mpty2\x8a\x01\n\x0bUserService\x12$\n\x08\x61\x64\x64_user\x12\x0b.users.User\x1a\x0b.users.User\x12)\n\x0b\x64\x65lete_user\x12\r.users.UserId\x1a\x0b.users.User\x12*\n\tget_users\x12\x0c.users.Empty\x1a\x0f.users.UserListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=36
  _globals['_USER']._serialized_end=118
  _globals['_USERID']._serialized_start=120
  _globals['_USERID']._serialized_end=140
  _globals['_USERLIST']._serialized_start=142
  _globals['_USERLIST']._serialized_end=179
  _globals['_EMPTY']._serialized_start=181
  _globals['_EMPTY']._serialized_end=188
  _globals['_USERSERVICE']._serialized_start=191
  _globals['_USERSERVICE']._serialized_end=329
# @@protoc_insertion_point(module_scope)
